image: node:14-alpine

stages:
  - pages

before_script:
  - yarn

cache:
  paths:
    - node_modules

pages:
  stage: pages
  script:
    - yarn run build
    - mkdir public
    - cp -r build public
  artifacts:
    paths:
      - public
